// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: tunnelpb/tunnel.proto

package tunnelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerToEndpoint is a wrapper for messages sent from the Server (APS) to the Endpoint client.
type ServerToEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for the message, used for request/response correlation and cancellations.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerToEndpoint_Request
	//	*ServerToEndpoint_Cancel
	//	*ServerToEndpoint_Heartbeat
	Payload       isServerToEndpoint_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToEndpoint) Reset() {
	*x = ServerToEndpoint{}
	mi := &file_tunnelpb_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToEndpoint) ProtoMessage() {}

func (x *ServerToEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_tunnelpb_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToEndpoint.ProtoReflect.Descriptor instead.
func (*ServerToEndpoint) Descriptor() ([]byte, []int) {
	return file_tunnelpb_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *ServerToEndpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerToEndpoint) GetPayload() isServerToEndpoint_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerToEndpoint) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Payload.(*ServerToEndpoint_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *ServerToEndpoint) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Payload.(*ServerToEndpoint_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ServerToEndpoint) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ServerToEndpoint_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isServerToEndpoint_Payload interface {
	isServerToEndpoint_Payload()
}

type ServerToEndpoint_Request struct {
	Request *Request `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type ServerToEndpoint_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"`
}

type ServerToEndpoint_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*ServerToEndpoint_Request) isServerToEndpoint_Payload() {}

func (*ServerToEndpoint_Cancel) isServerToEndpoint_Payload() {}

func (*ServerToEndpoint_Heartbeat) isServerToEndpoint_Payload() {}

// EndpointToServer is a wrapper for messages sent from the Endpoint client to the Server (APS).
type EndpointToServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EndpointToServer_Registration
	//	*EndpointToServer_Response
	//	*EndpointToServer_Heartbeat
	Payload       isEndpointToServer_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointToServer) Reset() {
	*x = EndpointToServer{}
	mi := &file_tunnelpb_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointToServer) ProtoMessage() {}

func (x *EndpointToServer) ProtoReflect() protoreflect.Message {
	mi := &file_tunnelpb_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointToServer.ProtoReflect.Descriptor instead.
func (*EndpointToServer) Descriptor() ([]byte, []int) {
	return file_tunnelpb_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointToServer) GetPayload() isEndpointToServer_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EndpointToServer) GetRegistration() *RegistrationRequest {
	if x != nil {
		if x, ok := x.Payload.(*EndpointToServer_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *EndpointToServer) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Payload.(*EndpointToServer_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *EndpointToServer) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*EndpointToServer_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isEndpointToServer_Payload interface {
	isEndpointToServer_Payload()
}

type EndpointToServer_Registration struct {
	Registration *RegistrationRequest `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type EndpointToServer_Response struct {
	Response *Response `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type EndpointToServer_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*EndpointToServer_Registration) isEndpointToServer_Payload() {}

func (*EndpointToServer_Response) isEndpointToServer_Payload() {}

func (*EndpointToServer_Heartbeat) isEndpointToServer_Payload() {}

// RegistrationRequest is the very first message sent by the client to identify itself.
type RegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointName  string                 `protobuf:"bytes,1,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"`
	TunnelName    string                 `protobuf:"bytes,2,opt,name=tunnel_name,json=tunnelName,proto3" json:"tunnel_name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // For authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_tunnelpb_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnelpb_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_tunnelpb_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *RegistrationRequest) GetEndpointName() string {
	if x != nil {
		return x.EndpointName
	}
	return ""
}

func (x *RegistrationRequest) GetTunnelName() string {
	if x != nil {
		return x.TunnelName
	}
	return ""
}

func (x *RegistrationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Request is a raw HTTP request forwarded from the server to the endpoint.
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The original URL the request was made to.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// The raw bytes of the HTTP request (e.g., from httputil.DumpRequest).
	// This data will be encrypted by the server before sending.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_tunnelpb_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_tunnelpb_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_tunnelpb_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Response is a raw HTTP response sent back from the endpoint to the server.
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlates with the Request ID from ServerToEndpoint.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*Response_Data
	//	*Response_Error
	Content       isResponse_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_tunnelpb_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_tunnelpb_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_tunnelpb_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response) GetContent() isResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Response) GetData() []byte {
	if x != nil {
		if x, ok := x.Content.(*Response_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		if x, ok := x.Content.(*Response_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isResponse_Content interface {
	isResponse_Content()
}

type Response_Data struct {
	// The raw bytes of the HTTP response (e.g., from httputil.DumpResponse).
	// This data will be encrypted by the client before sending.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type Response_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*Response_Data) isResponse_Content() {}

func (*Response_Error) isResponse_Content() {}

// Cancel is a message from the server to cancel an in-flight request.
type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_tunnelpb_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_tunnelpb_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_tunnelpb_tunnel_proto_rawDescGZIP(), []int{5}
}

// Heartbeat is a message to check if the connection is still alive.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_tunnelpb_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_tunnelpb_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_tunnelpb_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_tunnelpb_tunnel_proto protoreflect.FileDescriptor

const file_tunnelpb_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x15tunnelpb/tunnel.proto\x12\x06tunnel\"\xb7\x01\n" +
	"\x10ServerToEndpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\arequest\x18\x02 \x01(\v2\x0f.tunnel.RequestH\x00R\arequest\x12(\n" +
	"\x06cancel\x18\x03 \x01(\v2\x0e.tunnel.CancelH\x00R\x06cancel\x121\n" +
	"\theartbeat\x18\x04 \x01(\v2\x11.tunnel.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\xc3\x01\n" +
	"\x10EndpointToServer\x12A\n" +
	"\fregistration\x18\x01 \x01(\v2\x1b.tunnel.RegistrationRequestH\x00R\fregistration\x12.\n" +
	"\bresponse\x18\x02 \x01(\v2\x10.tunnel.ResponseH\x00R\bresponse\x121\n" +
	"\theartbeat\x18\x03 \x01(\v2\x11.tunnel.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"w\n" +
	"\x13RegistrationRequest\x12#\n" +
	"\rendpoint_name\x18\x01 \x01(\tR\fendpointName\x12\x1f\n" +
	"\vtunnel_name\x18\x02 \x01(\tR\n" +
	"tunnelName\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"/\n" +
	"\aRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"S\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\t\n" +
	"\acontent\"\b\n" +
	"\x06Cancel\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp2T\n" +
	"\rTunnelService\x12C\n" +
	"\tEstablish\x12\x18.tunnel.EndpointToServer\x1a\x18.tunnel.ServerToEndpoint(\x010\x01B\fZ\n" +
	"./tunnelpbb\x06proto3"

var (
	file_tunnelpb_tunnel_proto_rawDescOnce sync.Once
	file_tunnelpb_tunnel_proto_rawDescData []byte
)

func file_tunnelpb_tunnel_proto_rawDescGZIP() []byte {
	file_tunnelpb_tunnel_proto_rawDescOnce.Do(func() {
		file_tunnelpb_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tunnelpb_tunnel_proto_rawDesc), len(file_tunnelpb_tunnel_proto_rawDesc)))
	})
	return file_tunnelpb_tunnel_proto_rawDescData
}

var file_tunnelpb_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tunnelpb_tunnel_proto_goTypes = []any{
	(*ServerToEndpoint)(nil),    // 0: tunnel.ServerToEndpoint
	(*EndpointToServer)(nil),    // 1: tunnel.EndpointToServer
	(*RegistrationRequest)(nil), // 2: tunnel.RegistrationRequest
	(*Request)(nil),             // 3: tunnel.Request
	(*Response)(nil),            // 4: tunnel.Response
	(*Cancel)(nil),              // 5: tunnel.Cancel
	(*Heartbeat)(nil),           // 6: tunnel.Heartbeat
}
var file_tunnelpb_tunnel_proto_depIdxs = []int32{
	3, // 0: tunnel.ServerToEndpoint.request:type_name -> tunnel.Request
	5, // 1: tunnel.ServerToEndpoint.cancel:type_name -> tunnel.Cancel
	6, // 2: tunnel.ServerToEndpoint.heartbeat:type_name -> tunnel.Heartbeat
	2, // 3: tunnel.EndpointToServer.registration:type_name -> tunnel.RegistrationRequest
	4, // 4: tunnel.EndpointToServer.response:type_name -> tunnel.Response
	6, // 5: tunnel.EndpointToServer.heartbeat:type_name -> tunnel.Heartbeat
	1, // 6: tunnel.TunnelService.Establish:input_type -> tunnel.EndpointToServer
	0, // 7: tunnel.TunnelService.Establish:output_type -> tunnel.ServerToEndpoint
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tunnelpb_tunnel_proto_init() }
func file_tunnelpb_tunnel_proto_init() {
	if File_tunnelpb_tunnel_proto != nil {
		return
	}
	file_tunnelpb_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerToEndpoint_Request)(nil),
		(*ServerToEndpoint_Cancel)(nil),
		(*ServerToEndpoint_Heartbeat)(nil),
	}
	file_tunnelpb_tunnel_proto_msgTypes[1].OneofWrappers = []any{
		(*EndpointToServer_Registration)(nil),
		(*EndpointToServer_Response)(nil),
		(*EndpointToServer_Heartbeat)(nil),
	}
	file_tunnelpb_tunnel_proto_msgTypes[4].OneofWrappers = []any{
		(*Response_Data)(nil),
		(*Response_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tunnelpb_tunnel_proto_rawDesc), len(file_tunnelpb_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tunnelpb_tunnel_proto_goTypes,
		DependencyIndexes: file_tunnelpb_tunnel_proto_depIdxs,
		MessageInfos:      file_tunnelpb_tunnel_proto_msgTypes,
	}.Build()
	File_tunnelpb_tunnel_proto = out.File
	file_tunnelpb_tunnel_proto_goTypes = nil
	file_tunnelpb_tunnel_proto_depIdxs = nil
}
