// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: tunnelpb/tunnel.proto

package tunnelpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TunnelService_Establish_FullMethodName = "/tunnel.TunnelService/Establish"
)

// TunnelServiceClient is the client API for TunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TunnelService defines the bidirectional streaming RPC for tunneling.
type TunnelServiceClient interface {
	// Establish creates a persistent bidirectional stream.
	// The first message from the client MUST be a RegistrationRequest.
	Establish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EndpointToServer, ServerToEndpoint], error)
}

type tunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelServiceClient(cc grpc.ClientConnInterface) TunnelServiceClient {
	return &tunnelServiceClient{cc}
}

func (c *tunnelServiceClient) Establish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EndpointToServer, ServerToEndpoint], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TunnelService_ServiceDesc.Streams[0], TunnelService_Establish_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EndpointToServer, ServerToEndpoint]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_EstablishClient = grpc.BidiStreamingClient[EndpointToServer, ServerToEndpoint]

// TunnelServiceServer is the server API for TunnelService service.
// All implementations must embed UnimplementedTunnelServiceServer
// for forward compatibility.
//
// TunnelService defines the bidirectional streaming RPC for tunneling.
type TunnelServiceServer interface {
	// Establish creates a persistent bidirectional stream.
	// The first message from the client MUST be a RegistrationRequest.
	Establish(grpc.BidiStreamingServer[EndpointToServer, ServerToEndpoint]) error
	mustEmbedUnimplementedTunnelServiceServer()
}

// UnimplementedTunnelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTunnelServiceServer struct{}

func (UnimplementedTunnelServiceServer) Establish(grpc.BidiStreamingServer[EndpointToServer, ServerToEndpoint]) error {
	return status.Errorf(codes.Unimplemented, "method Establish not implemented")
}
func (UnimplementedTunnelServiceServer) mustEmbedUnimplementedTunnelServiceServer() {}
func (UnimplementedTunnelServiceServer) testEmbeddedByValue()                       {}

// UnsafeTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServiceServer will
// result in compilation errors.
type UnsafeTunnelServiceServer interface {
	mustEmbedUnimplementedTunnelServiceServer()
}

func RegisterTunnelServiceServer(s grpc.ServiceRegistrar, srv TunnelServiceServer) {
	// If the following call pancis, it indicates UnimplementedTunnelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TunnelService_ServiceDesc, srv)
}

func _TunnelService_Establish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServiceServer).Establish(&grpc.GenericServerStream[EndpointToServer, ServerToEndpoint]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_EstablishServer = grpc.BidiStreamingServer[EndpointToServer, ServerToEndpoint]

// TunnelService_ServiceDesc is the grpc.ServiceDesc for TunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.TunnelService",
	HandlerType: (*TunnelServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Establish",
			Handler:       _TunnelService_Establish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tunnelpb/tunnel.proto",
}

const (
	RelayService_EstablishRelay_FullMethodName = "/tunnel.RelayService/EstablishRelay"
)

// RelayServiceClient is the client API for RelayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RelayService provides relay functionality for multi-hop connections
type RelayServiceClient interface {
	// EstablishRelay creates a persistent bidirectional relay stream
	EstablishRelay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RelayMessage, RelayMessage], error)
}

type relayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayServiceClient(cc grpc.ClientConnInterface) RelayServiceClient {
	return &relayServiceClient{cc}
}

func (c *relayServiceClient) EstablishRelay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RelayMessage, RelayMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RelayService_ServiceDesc.Streams[0], RelayService_EstablishRelay_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RelayMessage, RelayMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RelayService_EstablishRelayClient = grpc.BidiStreamingClient[RelayMessage, RelayMessage]

// RelayServiceServer is the server API for RelayService service.
// All implementations must embed UnimplementedRelayServiceServer
// for forward compatibility.
//
// RelayService provides relay functionality for multi-hop connections
type RelayServiceServer interface {
	// EstablishRelay creates a persistent bidirectional relay stream
	EstablishRelay(grpc.BidiStreamingServer[RelayMessage, RelayMessage]) error
	mustEmbedUnimplementedRelayServiceServer()
}

// UnimplementedRelayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayServiceServer struct{}

func (UnimplementedRelayServiceServer) EstablishRelay(grpc.BidiStreamingServer[RelayMessage, RelayMessage]) error {
	return status.Errorf(codes.Unimplemented, "method EstablishRelay not implemented")
}
func (UnimplementedRelayServiceServer) mustEmbedUnimplementedRelayServiceServer() {}
func (UnimplementedRelayServiceServer) testEmbeddedByValue()                      {}

// UnsafeRelayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayServiceServer will
// result in compilation errors.
type UnsafeRelayServiceServer interface {
	mustEmbedUnimplementedRelayServiceServer()
}

func RegisterRelayServiceServer(s grpc.ServiceRegistrar, srv RelayServiceServer) {
	// If the following call pancis, it indicates UnimplementedRelayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayService_ServiceDesc, srv)
}

func _RelayService_EstablishRelay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RelayServiceServer).EstablishRelay(&grpc.GenericServerStream[RelayMessage, RelayMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RelayService_EstablishRelayServer = grpc.BidiStreamingServer[RelayMessage, RelayMessage]

// RelayService_ServiceDesc is the grpc.ServiceDesc for RelayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.RelayService",
	HandlerType: (*RelayServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EstablishRelay",
			Handler:       _RelayService_EstablishRelay_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tunnelpb/tunnel.proto",
}

const (
	RoutingService_CalculateRoutes_FullMethodName = "/tunnel.RoutingService/CalculateRoutes"
	RoutingService_UpdateRouteInfo_FullMethodName = "/tunnel.RoutingService/UpdateRouteInfo"
)

// RoutingServiceClient is the client API for RoutingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RoutingService provides route optimization services
type RoutingServiceClient interface {
	// CalculateRoutes calculates optimal routes between endpoints
	CalculateRoutes(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
	// UpdateRouteInfo updates route information
	UpdateRouteInfo(ctx context.Context, in *RouteUpdate, opts ...grpc.CallOption) (*RouteUpdateResponse, error)
}

type routingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingServiceClient(cc grpc.ClientConnInterface) RoutingServiceClient {
	return &routingServiceClient{cc}
}

func (c *routingServiceClient) CalculateRoutes(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, RoutingService_CalculateRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) UpdateRouteInfo(ctx context.Context, in *RouteUpdate, opts ...grpc.CallOption) (*RouteUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteUpdateResponse)
	err := c.cc.Invoke(ctx, RoutingService_UpdateRouteInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutingServiceServer is the server API for RoutingService service.
// All implementations must embed UnimplementedRoutingServiceServer
// for forward compatibility.
//
// RoutingService provides route optimization services
type RoutingServiceServer interface {
	// CalculateRoutes calculates optimal routes between endpoints
	CalculateRoutes(context.Context, *RouteRequest) (*RouteResponse, error)
	// UpdateRouteInfo updates route information
	UpdateRouteInfo(context.Context, *RouteUpdate) (*RouteUpdateResponse, error)
	mustEmbedUnimplementedRoutingServiceServer()
}

// UnimplementedRoutingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutingServiceServer struct{}

func (UnimplementedRoutingServiceServer) CalculateRoutes(context.Context, *RouteRequest) (*RouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateRoutes not implemented")
}
func (UnimplementedRoutingServiceServer) UpdateRouteInfo(context.Context, *RouteUpdate) (*RouteUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRouteInfo not implemented")
}
func (UnimplementedRoutingServiceServer) mustEmbedUnimplementedRoutingServiceServer() {}
func (UnimplementedRoutingServiceServer) testEmbeddedByValue()                        {}

// UnsafeRoutingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingServiceServer will
// result in compilation errors.
type UnsafeRoutingServiceServer interface {
	mustEmbedUnimplementedRoutingServiceServer()
}

func RegisterRoutingServiceServer(s grpc.ServiceRegistrar, srv RoutingServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoutingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutingService_ServiceDesc, srv)
}

func _RoutingService_CalculateRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).CalculateRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_CalculateRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).CalculateRoutes(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_UpdateRouteInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).UpdateRouteInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_UpdateRouteInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).UpdateRouteInfo(ctx, req.(*RouteUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

// RoutingService_ServiceDesc is the grpc.ServiceDesc for RoutingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.RoutingService",
	HandlerType: (*RoutingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateRoutes",
			Handler:    _RoutingService_CalculateRoutes_Handler,
		},
		{
			MethodName: "UpdateRouteInfo",
			Handler:    _RoutingService_UpdateRouteInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tunnelpb/tunnel.proto",
}
